version: "3"
services:
    postgres:
        container_name: db
        image: postgres:latest
        ports:
            - "5434:5432"
        env_file:
            - .env
        volumes:
           - postgres:/var/lib/posgresql/data

    back:
        container_name: back
        image: node:lts-alpine
        restart: unless-stopped
        ports: 
            - "3000:3000"
            - "5555:5555"
        env_file:
            - .env
#        command: "tail -f"
#       command: sh -c "apk add bash vim ; npm i -g @nestjs/cli; npm --prefix /back/nestjs-api-tutorial install; npm add -D prisma ; npm add @prisma/client ; npm run --prefix /back/nestjs-api-tutorial start:dev;" #npx prisma generate; npx prisma migrate dev; npm run start:dev"
#        command: sh -c "apk add bash vim ; npm i -g @nestjs/cli; cd nestjs-api-tutorial ; npm install; npx prisma generate; npx prisma migrate dev; npm run start:dev;" # npm run start:dev"
        command: sh -c "npm i -g @nestjs/cli; npm install; npm run start:dev;"
        volumes:
            - "./backend:/back"
        working_dir: /back

        #    frontend:
        #        container_name: front
        #        image: node:lts-alpine
        #        restart: unless-stopped
        #        ports:
        #            - "4200:4200"
        #        # command: "tail -f"
        #        command: sh -c "apk add bash && npm install && npm start"
        #        volumes:
        #            - "./frontend:/front"
        #        working_dir: /front

volumes:
    postgres:
    test_db_vol:
